[tool.uv.workspace]
members = ["packages/*", "apps/*"]

[tool.uv.sources]
reflex-chessboard = { workspace = true }
reflex-chess-model = { workspace = true }
reflex-chess-notation = { workspace = true }
reflex-chess-viewer = { workspace = true }
reflex-chess-trainer = { workspace = true }

[dependency-groups]
dev = [
  "ruff>=0.14.10",
  "pytest>=9.0.2",
  "pyright>=1.1.390",
]


